### PR TITLE
Misc tiny fixes

### PR DESCRIPTION
**Pull request by ottok**
- Run 'wrap-and-sort -ast'
- Fix docs.microsoft.com link so it does not redirect
- As project mandates signed commits, tell contributors how to configure git so commits are signed automatically

### CODE REVIEW

**Comment by pabs3** [comment]
Split up into separate logical commits, adjusted some of them and merged all of them.

**Comment by ottok** [comment]
Please just give feedback and let authors have [ownership](https://optimizedbyotto.com/post/how-to-code-review/#honor-original-code-let-submitters-feel-ownership). The only fun I get out of doing drive-by-contributions is a purple badge on my GitHub profile and now you robbed it..

**Comment by pabs3** [comment]
For such a small PR I didn't think it worth the back-and-forth.
The commits were attributed to you, so your purple badge is safe :)

**Comment by ottok** [comment]
Next time give feedback and wait for a couple of days to see if contributor wants to learn and polish submission, and only then take over ownership of the submission, please.

There is no purple badge for PRs that are marked as closed/rejected.

image

**Comment by pabs3** [comment]
I have removed the commits and reopened the PR.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by ottok** [comment]
I can update this or you can just merge/pull
https://github.com/collab-qa/check-all-the-things/pull/12 and branch master
will end up with 5 separate commits as you preferred.

**Comment by ottok** [comment]
The contents of this branch matches now the feedback/form you requested, and additionally all commits are signed as per project README.

**Pull request merged**
